version: '3.8'

services:
  # PostgreSQL for user-service
  user-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stillfresh_userdb
      POSTGRES_USER: stillfreshuser
      POSTGRES_PASSWORD: FreshStill011User
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
      - ./init-user.sql:/docker-entrypoint-initdb.d/init.sql

  # PostgreSQL for vendor-service
  vendor-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stillfresh_vendordb
      POSTGRES_USER: stillfreshvendor
      POSTGRES_PASSWORD: FreshStill011Vendor
    ports:
      - "5433:5432"
    volumes:
      - vendor_postgres_data:/var/lib/postgresql/data
      - ./init-vendor.sql:/docker-entrypoint-initdb.d/init.sql 

  # Redis for caching
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Eureka service discovery
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - user-postgres
      - vendor-postgres

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - user-service
      - vendor-service  # Added vendor-service dependency
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - user-postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Vendor Service
  vendor-service:
    build: ./vendor-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - vendor-postgres  # Vendor service depends on vendor-postgres for DB
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  user_postgres_data:
  vendor_postgres_data:
