services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
