version: '3.8'

services:
  # Zookeeper for Kafka coordination
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - stillfresh_network

  # Kafka Broker
  kafka:
    image: bitnami/kafka:3.4.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_MODE=true
      - KAFKA_KRAFT_CLUSTER_ID=qk6eNRoKT6aFw3XkMJT-dw  # Set this or keep consistent if changed
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093  # Required for single-node setup
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - stillfresh_network

  # PostgreSQL for user-service
  user-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stillfresh_userdb
      POSTGRES_USER: stillfreshuser
      POSTGRES_PASSWORD: FreshStill011User
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
      - ./init-user.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stillfresh_network

  # PostgreSQL for vendor-service
  vendor-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stillfresh_vendordb
      POSTGRES_USER: stillfreshvendor
      POSTGRES_PASSWORD: FreshStill011Vendor
    ports:
      - "5433:5432"
    volumes:
      - vendor_postgres_data:/var/lib/postgresql/data
      - ./init-vendor.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - stillfresh_network

  # PostgreSQL for authorization-service
  auth-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: stillfresh_authdb
      POSTGRES_USER: stillfreshauth
      POSTGRES_PASSWORD: FreshStill011Auth
    ports:
      - "5434:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./init-auth.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - stillfresh_network

  # Redis for caching and token blacklisting
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - stillfresh_network

  # Eureka service discovery
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - user-postgres
      - vendor-postgres
      - auth-postgres
    networks:
      - stillfresh_network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - authorization-service
      - user-service
      - vendor-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - stillfresh_network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - user-postgres
      - redis
      - kafka # Depends on Kafka for messaging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - stillfresh_network

  # Vendor Service
  vendor-service:
    build: ./vendor-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - vendor-postgres
      - redis
      - kafka # Depends on Kafka for messaging
    environment:
      - KAFKA_BROKER=kafka:9092
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - stillfresh_network

  # Authorization Service
  authorization-service:
    build: ./authorization-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - auth-postgres
      - redis
      - kafka # Depends on Kafka for messaging
    environment:
      - KAFKA_BROKER=kafka:9092
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - stillfresh_network

volumes:
  user_postgres_data:
  vendor_postgres_data:
  auth_postgres_data:

networks:
  stillfresh_network:
    driver: bridge
