server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/stillfresh  # PostgreSQL database URL
    driverClassName: org.postgresql.Driver            # PostgreSQL driver class
    username: stillfreshuser                          # PostgreSQL username
    password: FreshStill011                            # PostgreSQL password (ensure this is secure and managed properly)
  jpa:
    hibernate:
      ddl-auto: update                                # Automatically updates the database schema
    show-sql: true                                    # Shows SQL queries in the logs
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL dialect for Hibernate

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # Eureka server URL