# File: user-service/src/main/resources/application.yml
server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-postgres:5432/stillfresh_userdb
    driverClassName: org.postgresql.Driver
    username: stillfreshuser
    password: FreshStill011User
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis  # Use Redis for caching

  data:
    redis:
      host: redis  # The service name used in docker-compose.yml
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
      timeout: 60000  # Timeout in milliseconds
      
logging:
  level:
    '[org.springframework.cache]': DEBUG  # Enable debug logging for cache operations

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

