package com.stillfresh.app.paymentservice.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * Records the financial context of each payment request.
 * Created when a PaymentIntent is successfully authorised; used by the ledger
 * when the intent is later captured.
 */
@Entity
@Table(name = "payment_transactions",
       indexes = {
           @Index(name = "idx_pt_request_id",       columnList = "request_id",        unique = true),
           @Index(name = "idx_pt_payment_intent_id", columnList = "payment_intent_id", unique = true),
           @Index(name = "idx_pt_vendor_id",         columnList = "vendor_id")
       })
public class PaymentTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Correlation ID generated by order-service before order exists in DB. */
    @Column(name = "request_id", nullable = false, unique = true, length = 64)
    private String requestId;

    /** Stripe PaymentIntent ID, set once the PI is created. */
    @Column(name = "payment_intent_id", unique = true, length = 255)
    private String paymentIntentId;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "vendor_id")
    private Long vendorId;

    @Column(name = "offer_id")
    private Long offerId;

    /** Total amount authorised, in minor currency units (e.g. cents). */
    @Column(name = "gross_amount_cents", nullable = false)
    private Long grossAmountCents;

    /** Platform fee calculated at authorisation time, in minor currency units. */
    @Column(name = "platform_fee_cents", nullable = false)
    private Long platformFeeCents;

    /** Net amount to be credited to the vendor, in minor currency units. */
    @Column(name = "net_amount_cents", nullable = false)
    private Long netAmountCents;

    /** Platform fee percentage applied at authorisation time (e.g. 10.0). */
    @Column(name = "fee_percent_applied")
    private Double feePercentApplied;

    /** ISO 4217 currency code. */
    @Column(name = "currency", nullable = false, length = 8)
    private String currency;

    /** True once ledger entries have been written for this transaction. */
    @Column(name = "ledger_written", nullable = false)
    private boolean ledgerWritten = false;

    /**
     * True once a PaymentSuccessEvent has been published for this authorization.
     * Used to deduplicate between AllSecure's synchronous result and its async callback.
     * columnDefinition supplies a DB default so the column can be added to a populated table.
     */
    @Column(name = "success_notified", nullable = false, columnDefinition = "boolean not null default false")
    private boolean successNotified = false;

    /** AllSecure 3DS redirect URL when order-time authentication is required. */
    @Column(name = "redirect_url", length = 2048)
    private String redirectUrl;

    @Enumerated(EnumType.STRING)
    @Column(name = "authorization_status", nullable = false, length = 32)
    private AuthorizationStatus authorizationStatus = AuthorizationStatus.PROCESSING;

    @Column(name = "failure_reason", length = 512)
    private String failureReason;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    public PaymentTransaction() {}

    // ── Getters & Setters ────────────────────────────────────────────────────

    public Long getId() { return id; }

    public String getRequestId() { return requestId; }
    public void setRequestId(String requestId) { this.requestId = requestId; }

    public String getPaymentIntentId() { return paymentIntentId; }
    public void setPaymentIntentId(String paymentIntentId) { this.paymentIntentId = paymentIntentId; }

    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }

    public Long getVendorId() { return vendorId; }
    public void setVendorId(Long vendorId) { this.vendorId = vendorId; }

    public Long getOfferId() { return offerId; }
    public void setOfferId(Long offerId) { this.offerId = offerId; }

    public Long getGrossAmountCents() { return grossAmountCents; }
    public void setGrossAmountCents(Long grossAmountCents) { this.grossAmountCents = grossAmountCents; }

    public Long getPlatformFeeCents() { return platformFeeCents; }
    public void setPlatformFeeCents(Long platformFeeCents) { this.platformFeeCents = platformFeeCents; }

    public Long getNetAmountCents() { return netAmountCents; }
    public void setNetAmountCents(Long netAmountCents) { this.netAmountCents = netAmountCents; }

    public Double getFeePercentApplied() { return feePercentApplied; }
    public void setFeePercentApplied(Double feePercentApplied) { this.feePercentApplied = feePercentApplied; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public boolean isLedgerWritten() { return ledgerWritten; }
    public void setLedgerWritten(boolean ledgerWritten) { this.ledgerWritten = ledgerWritten; }

    public boolean isSuccessNotified() { return successNotified; }
    public void setSuccessNotified(boolean successNotified) { this.successNotified = successNotified; }

    public String getRedirectUrl() { return redirectUrl; }
    public void setRedirectUrl(String redirectUrl) { this.redirectUrl = redirectUrl; }

    public AuthorizationStatus getAuthorizationStatus() { return authorizationStatus; }
    public void setAuthorizationStatus(AuthorizationStatus authorizationStatus) {
        this.authorizationStatus = authorizationStatus;
    }

    public String getFailureReason() { return failureReason; }
    public void setFailureReason(String failureReason) { this.failureReason = failureReason; }

    public Instant getCreatedAt() { return createdAt; }
}
