# File: eureka-server/src/main/resources/application.yml
server:
  port: 8761

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
